-keepattributes Signature
-keepattributes *Annotation*
-keep class com.google.gson.stream.** { *; }
-keep class com.google.gson.examples.android.model.** { *; }
-keep class * implements com.google.gson.TypeAdapter { *; }
-keep class com.google.gson.internal.LinkedTreeMap { *; }
-keep class com.kc.composewallpaper.model.** { *; }